#!/bin/sh -e

# gentoo-chroot DIR [CMD..]

script="${0##*/}"

die(){
  printf '%s\n' "$1" >&2
  exit 1
}

(( EUID == 0 )) die 'Run as root'

: ${CHROOT:=$1}; shift


if [ "$#" -lt 1 ]; then
  die "Usage: $script <mountpoint> <shell>"
fi

#zpool import -N -R ${CHROOT=-/mnt} ${ZPOOL=:zroot}
#zfs load-key ${ZPOOL}
#zfs mount ${ZPOOL}/ROOT/${ROOTFS=-gentoo}

#[ -d ${CHROOT}/boot/efi ] || mkdir -p ${CHROOT}/boot/efi
#mount LABEL=EFI ${CHROOT}/boot/efi

mount --rbind /dev  ${CHROOT}/dev
mount --make-rslave ${CHROOT}/dev

mount --types proc /proc ${CHROOT}/proc

mount --rbind /sys  ${CHROOT}/sys
mount --make-rslave ${CHROOT}/sys

mount --rbind /tmp ${CHROOT}/tmp
mount --bind /run  ${CHROOT}/run


#
# ENTRY POINT CHROOT
#

printf "\033[1m=> Entering chroot ${CHROOT}\033[m\n"; 
chroot ${CHROOT} ${SHELL:=/bin/bash}
