#!/bin/sh -e

# gentoo-chroot DIR [CMD..]

script="${0##*/}"

die(){
  printf '%s\n' "$1" >&2
  exit 1
}

(( EUID == 0 )) die 'Run as root'

: ${CHROOT:=$1}; shift


if [ "$#" -lt 1 ]; then
  die "Usage: $script <mountpoint> <shell>"
fi


mount --rbind /dev  ${CHROOT}/dev
mount --make-rslave ${CHROOT}/dev
mount --rbind /sys  ${CHROOT}/sys
mount --make-rslave ${CHROOT}/sys
mount --types proc /proc ${CHROOT}/proc
mount --rbind /tmp ${CHROOT}/tmp
mount --bind /run  ${CHROOT}/run


#
# ENTRY POINT CHROOT
#

printf "\033[1m=> Entering chroot ${CHROOT}\033[m\n"; 
chroot ${CHROOT} ${SHELL:=/bin/bash}
