#!/bin/sh

. ~/lib/colors.sh
. ~/lib/functions.sh
#. ~/lib/helpers.sh
#. ~/lib/path.sh

msg "direnv loading ~/.config/direnv/direnvrc"

newline(){ printf "\n"; }

append_path(){
  case ":${PATH}:" in
  *":${1}:"*) ;;
           *)  PATH="${PATH:+$PATH:}$1"
  esac
}


prepend_path(){
  case ":$PATH:" in
    *":$1:"*) ;;
           *) PATH="$1${PATH:+:$PATH}";;
  esac
}
