#!/bin/sh

. ~/lib/colors.sh
. ~/lib/functions.sh
#. ~/lib/helpers.sh
#. ~/lib/path.sh


newline(){ printf "\n"; }

prepend_path(){
  case ":$PATH:" in
    *":$1:"*) ;;
           *) PATH="$1${PATH:+:$PATH}";;
  esac
}

msg "direnv loading ~/.config/direnv/direnvrc"
